### ISSUE TITLE
logging in issue

### ISSUE THREAD

**Issue by losial** [bwallace/abstrackr-web#87]
hello,
my password stopped working recently and I could not log into abstrackr anymore.
I tried to reset the password several times but even new passwords send by the system do not work. I tried to use different devices and web browsers, but it did not help.
I would appreciate any help resolving this issue, as I am running a screening for meta-analysis and regaining access to it is quite urgent and critical for me. With kind regards, Losia

**Comment by losial** [comment]
sorry, my mistake, its now resolved

**Comment by bwallace** [comment]
OK, good. In the future, the GitHub issues page is not really the right
place for things like this, unless you think it's a general bug. Feel free
to email directly instead. Thanks.

On Tue, Jun 9, 2015 at 12:38 AM, losial <notifications@github.com> wrote:

> Closed #87 <https://github.com/bwallace/abstrackr-web/issues/87>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwallace/abstrackr-web/issues/87#event-325958900>.
>



-- 
byron
